version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - PORT=3000
        - API_HOST=backend:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - PORT=3000
